import { Question } from '../src/types';
import { INITIAL_QUESTIONS } from '../src/data/seed';
import * as fs from 'fs';
import * as path from 'path';

// Math expansion (Target 55+ questions)
const additionalMath: Question[] = [
  // Equivalent fractions
  {
    id: 'q-eq-7',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-equivalent-fractions',
    gradeLevel: 6,
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Which fraction is equivalent to 3/5?',
    options: [
      { id: 'a', text: '6/10' },
      { id: 'b', text: '5/3' },
      { id: 'c', text: '9/20' },
      { id: 'd', text: '4/10' },
    ],
    correctAnswer: 'a',
    explanation: 'Multiplying numerator and denominator by 2 gives 6/10.',
    hint: 'Multiply both top and bottom by 2.',
    estimatedSeconds: 12,
  },
  {
    id: 'q-eq-8',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-equivalent-fractions',
    gradeLevel: 6,
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Simplify the fraction 25/35 to its lowest terms.',
    options: [
      { id: 'a', text: '5/7' },
      { id: 'b', text: '3/5' },
      { id: 'c', text: '5/6' },
      { id: 'd', text: '4/7' },
    ],
    correctAnswer: 'a',
    explanation: 'Divide both 25 and 35 by their greatest common divisor (5) to get 5/7.',
    hint: 'Find the greatest common factor of 25 and 35.',
    estimatedSeconds: 14,
  },
  {
    id: 'q-eq-9',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-equivalent-fractions',
    gradeLevel: 6,
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Find the missing numerator: ?/48 = 5/8',
    options: [
      { id: 'a', text: '30' },
      { id: 'b', text: '35' },
      { id: 'c', text: '25' },
      { id: 'd', text: '40' },
    ],
    correctAnswer: 'a',
    explanation: '8 × 6 = 48, so 5 × 6 = 30.',
    hint: 'Determine what 8 was multiplied by to reach 48.',
    estimatedSeconds: 16,
  },
  {
    id: 'q-eq-10',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-equivalent-fractions',
    gradeLevel: 6,
    difficulty: 4,
    type: 'multiple_choice',
    prompt: 'Which of the following is NOT equivalent to 12/16?',
    options: [
      { id: 'a', text: '18/24' },
      { id: 'b', text: '3/4' },
      { id: 'c', text: '30/40' },
      { id: 'd', text: '14/20' },
    ],
    correctAnswer: 'd',
    explanation: '12/16 simplifies to 3/4. 14/20 simplifies to 7/10, which is not 3/4.',
    hint: 'Reduce 12/16 and each option to simplest form.',
    estimatedSeconds: 20,
  },
  {
    id: 'q-eq-11',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-equivalent-fractions',
    gradeLevel: 6,
    difficulty: 5,
    type: 'numeric',
    prompt: 'If (2k)/36 is equivalent to 7/12, what is the value of k?',
    correctAnswer: '10.5',
    explanation: '7/12 = 21/36. Therefore 2k = 21, so k = 10.5.',
    hint: 'Convert 7/12 to 36ths first.',
    estimatedSeconds: 25,
  },

  // Unlike Denominators
  {
    id: 'q-unlike-7',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-unlike-denominators',
    gradeLevel: 6,
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'What is the least common denominator (LCD) for 2/5 and 3/10?',
    options: [
      { id: 'a', text: '10' },
      { id: 'b', text: '15' },
      { id: 'c', text: '20' },
      { id: 'd', text: '50' },
    ],
    correctAnswer: 'a',
    explanation: 'Since 10 is a multiple of 5, the least common denominator is 10.',
    hint: 'Is the larger denominator a multiple of the smaller?',
    estimatedSeconds: 12,
  },
  {
    id: 'q-unlike-8',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-unlike-denominators',
    gradeLevel: 6,
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Calculate: 1/4 + 3/8 = ?',
    options: [
      { id: 'a', text: '5/8' },
      { id: 'b', text: '4/12' },
      { id: 'c', text: '4/8' },
      { id: 'd', text: '7/8' },
    ],
    correctAnswer: 'a',
    explanation: 'Convert 1/4 to 2/8. Then 2/8 + 3/8 = 5/8.',
    hint: 'Rewrite 1/4 with denominator 8.',
    estimatedSeconds: 15,
    misconceptionTags: ['adds_denominators_directly'],
  },
  {
    id: 'q-unlike-9',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-unlike-denominators',
    gradeLevel: 6,
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'Calculate: 2/3 - 1/6 = ? (in simplest form)',
    options: [
      { id: 'a', text: '1/2' },
      { id: 'b', text: '3/6' },
      { id: 'c', text: '1/3' },
      { id: 'd', text: '1/6' },
    ],
    correctAnswer: 'a',
    explanation: '2/3 = 4/6. Then 4/6 - 1/6 = 3/6 = 1/2.',
    hint: 'Convert 2/3 into sixths first.',
    estimatedSeconds: 18,
  },
  {
    id: 'q-unlike-10',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-unlike-denominators',
    gradeLevel: 6,
    difficulty: 4,
    type: 'multiple_choice',
    prompt: 'Calculate: 3/7 + 2/5 = ?',
    options: [
      { id: 'a', text: '29/35' },
      { id: 'b', text: '5/12' },
      { id: 'c', text: '31/35' },
      { id: 'd', text: '27/35' },
    ],
    correctAnswer: 'a',
    explanation: 'Common denominator is 35. 15/35 + 14/35 = 29/35.',
    hint: 'Multiply 3 by 5 and 2 by 7 to get common numerators.',
    estimatedSeconds: 22,
    misconceptionTags: ['adds_denominators_directly'],
  },
  {
    id: 'q-unlike-11',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-unlike-denominators',
    gradeLevel: 6,
    difficulty: 5,
    type: 'multiple_choice',
    prompt: 'Solve: 5/6 - 3/8 + 1/4 = ? (simplest form)',
    options: [
      { id: 'a', text: '17/24' },
      { id: 'b', text: '19/24' },
      { id: 'c', text: '7/12' },
      { id: 'd', text: '3/8' },
    ],
    correctAnswer: 'a',
    explanation: 'LCD of 6, 8, 4 is 24. 20/24 - 9/24 + 6/24 = 17/24.',
    hint: 'The least common denominator of 6, 8, and 4 is 24.',
    estimatedSeconds: 28,
  },

  // Multiplying fractions
  {
    id: 'q-fmult-1',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-fraction-multiplication',
    gradeLevel: 6,
    difficulty: 1,
    type: 'multiple_choice',
    prompt: 'Calculate: 1/2 × 1/3 = ?',
    options: [
      { id: 'a', text: '1/6' },
      { id: 'b', text: '2/5' },
      { id: 'c', text: '1/5' },
      { id: 'd', text: '5/6' },
    ],
    correctAnswer: 'a',
    explanation: 'Multiply numerators (1×1=1) and denominators (2×3=6) to get 1/6.',
    hint: 'Multiply the top numbers together and bottom numbers together.',
    estimatedSeconds: 12,
  },
  {
    id: 'q-fmult-2',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-fraction-multiplication',
    gradeLevel: 6,
    difficulty: 2,
    type: 'multiple_choice',
    prompt: 'Calculate: 3/4 × 2/5 = ? (in simplest form)',
    options: [
      { id: 'a', text: '3/10' },
      { id: 'b', text: '6/20' },
      { id: 'c', text: '5/9' },
      { id: 'd', text: '1/2' },
    ],
    correctAnswer: 'a',
    explanation: '3×2 = 6, 4×5 = 20. 6/20 reduces to 3/10.',
    hint: 'Multiply across, then simplify by dividing by 2.',
    estimatedSeconds: 15,
  },
  {
    id: 'q-fmult-3',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-fraction-multiplication',
    gradeLevel: 6,
    difficulty: 3,
    type: 'multiple_choice',
    prompt: 'What is 2/3 of 18?',
    options: [
      { id: 'a', text: '12' },
      { id: 'b', text: '10' },
      { id: 'c', text: '9' },
      { id: 'd', text: '14' },
    ],
    correctAnswer: 'a',
    explanation: '18 ÷ 3 = 6, and 6 × 2 = 12.',
    hint: 'Divide 18 by 3, then multiply the result by 2.',
    estimatedSeconds: 14,
  },
  {
    id: 'q-fmult-4',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-fraction-multiplication',
    gradeLevel: 6,
    difficulty: 4,
    type: 'multiple_choice',
    prompt: 'Calculate: 4/9 × 3/8 = ? (in simplest form)',
    options: [
      { id: 'a', text: '1/6' },
      { id: 'b', text: '12/72' },
      { id: 'c', text: '1/4' },
      { id: 'd', text: '2/9' },
    ],
    correctAnswer: 'a',
    explanation: 'Cross-canceling: (4/8 becomes 1/2) and (3/9 becomes 1/3). 1/3 × 1/2 = 1/6.',
    hint: 'Simplify diagonally before multiplying.',
    estimatedSeconds: 18,
  },
  {
    id: 'q-fmult-5',
    subjectId: 'math',
    topicId: 'fractions',
    skillId: 'skill-fraction-multiplication',
    gradeLevel: 6,
    difficulty: 5,
    type: 'multiple_choice',
    prompt: 'A recipe calls for 3/4 cup of sugar. If you make 2 and 1/2 times the recipe, how much sugar do you need?',
    options: [
      { id: 'a', text: '1 and 7/8 cups' },
      { id: 'b', text: '1 and 1/2 cups' },
      { id: 'c', text: '2 cups' },
      { id: 'd', text: '1 and 3/4 cups' },
    ],
    correctAnswer: 'a',
    explanation: '2 1/2 = 5/2. 3/4 × 5/2 = 15/8 = 1 7/8 cups.',
    hint: 'Convert 2 1/2 to improper fraction 5/2, then multiply.',
    estimatedSeconds: 24,
  },

  // Mental arithmetic & PEMDAS
  {
    id: 'q-ops-4',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-order-ops',
    gradeLevel: 6,
    difficulty: 1,
    type: 'numeric',
    prompt: 'Evaluate: 10 - 2 × 3 = ?',
    correctAnswer: '4',
    explanation: 'Multiply first: 2 × 3 = 6. Then 10 - 6 = 4.',
    hint: 'Multiplication comes before subtraction.',
    estimatedSeconds: 10,
  },
  {
    id: 'q-ops-5',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-order-ops',
    gradeLevel: 6,
    difficulty: 2,
    type: 'numeric',
    prompt: 'Evaluate: 4 + 16 ÷ 4 = ?',
    correctAnswer: '8',
    explanation: 'Division first: 16 ÷ 4 = 4. Then 4 + 4 = 8.',
    hint: 'Perform division before addition.',
    estimatedSeconds: 10,
  },
  {
    id: 'q-ops-6',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-order-ops',
    gradeLevel: 6,
    difficulty: 3,
    type: 'numeric',
    prompt: 'Evaluate: (8 + 2)² - 30 = ?',
    correctAnswer: '70',
    explanation: 'Parentheses: 8 + 2 = 10. Exponent: 10² = 100. Subtraction: 100 - 30 = 70.',
    hint: 'Do parentheses, then exponent, then subtraction.',
    estimatedSeconds: 15,
  },
  {
    id: 'q-ops-7',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-order-ops',
    gradeLevel: 6,
    difficulty: 4,
    type: 'numeric',
    prompt: 'Evaluate: 5 × (3 + 2) - 4² ÷ 2 = ?',
    correctAnswer: '17',
    explanation: 'Parentheses: 3+2=5. 5×5=25. Exponent: 4²=16. 16÷2=8. 25-8=17.',
    hint: 'Calculate parentheses and exponents before multiplication and division.',
    estimatedSeconds: 20,
  },
  {
    id: 'q-ops-8',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-order-ops',
    gradeLevel: 6,
    difficulty: 5,
    type: 'numeric',
    prompt: 'Evaluate: 100 - [4 × (5 + 3) + 2³] = ?',
    correctAnswer: '60',
    explanation: 'Inside brackets: 5+3=8. 4×8=32. 2³=8. 32+8=40. 100-40=60.',
    hint: 'Work your way from innermost parentheses outward.',
    estimatedSeconds: 25,
  },

  // Multiplication Fluency
  {
    id: 'q-mult-flu-3',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-rapid-mult',
    gradeLevel: 6,
    difficulty: 1,
    type: 'numeric',
    prompt: 'Evaluate: 12 × 6 = ?',
    correctAnswer: '72',
    explanation: '10 × 6 = 60, 2 × 6 = 12. 60 + 12 = 72.',
    hint: 'Think 10 × 6 plus 2 × 6.',
    estimatedSeconds: 8,
  },
  {
    id: 'q-mult-flu-4',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-rapid-mult',
    gradeLevel: 6,
    difficulty: 2,
    type: 'numeric',
    prompt: 'Evaluate: 15 × 6 = ?',
    correctAnswer: '90',
    explanation: '15 × 2 = 30, and 30 × 3 = 90.',
    hint: 'Multiply 15 by 2, then by 3.',
    estimatedSeconds: 10,
  },
  {
    id: 'q-mult-flu-5',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-rapid-mult',
    gradeLevel: 6,
    difficulty: 3,
    type: 'numeric',
    prompt: 'Evaluate: 24 × 5 = ?',
    correctAnswer: '120',
    explanation: 'Half of 24 is 12; multiply by 10 to get 120.',
    hint: 'Multiplying by 5 is the same as taking half and multiplying by 10.',
    estimatedSeconds: 12,
  },
  {
    id: 'q-mult-flu-6',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-rapid-mult',
    gradeLevel: 6,
    difficulty: 4,
    type: 'numeric',
    prompt: 'Evaluate: 16 × 25 = ?',
    correctAnswer: '400',
    explanation: '16 ÷ 4 = 4. 4 × 100 = 400.',
    hint: 'Four 25s make 100. How many groups of 4 are in 16?',
    estimatedSeconds: 15,
  },
  {
    id: 'q-mult-flu-7',
    subjectId: 'math',
    topicId: 'arithmetic',
    skillId: 'skill-rapid-mult',
    gradeLevel: 6,
    difficulty: 5,
    type: 'numeric',
    prompt: 'Evaluate: 32 × 15 = ?',
    correctAnswer: '480',
    explanation: '32 × 10 = 320, 32 × 5 = 160. 320 + 160 = 480.',
    hint: 'Multiply by 10, then add half of that amount.',
    estimatedSeconds: 16,
  },

  // One-Step Linear Equations
  {
    id: 'q-alg-3',
    subjectId: 'math',
    topicId: 'algebra',
    skillId: 'skill-linear-solve',
    gradeLevel: 6,
    difficulty: 1,
    type: 'numeric',
    prompt: 'Solve for x: x - 7 = 15. What is the value of x?',
    correctAnswer: '22',
    explanation: 'Add 7 to both sides: x = 15 + 7 = 22.',
    hint: 'Use the inverse of subtraction (add 7).',
    estimatedSeconds: 10,
  },
  {
    id: 'q-alg-4',
    subjectId: 'math',
    topicId: 'algebra',
    skillId: 'skill-linear-solve',
    gradeLevel: 6,
    difficulty: 2,
    type: 'numeric',
    prompt: 'Solve for m: m / 6 = 7. What is the value of m?',
    correctAnswer: '42',
    explanation: 'Multiply both sides by 6: m = 7 × 6 = 42.',
    hint: 'Use the inverse of division (multiply by 6).',
    estimatedSeconds: 10,
  },
  {
    id: 'q-alg-5',
    subjectId: 'math',
    topicId: 'algebra',
    skillId: 'skill-linear-solve',
    gradeLevel: 6,
    difficulty: 3,
    type: 'numeric',
    prompt: 'Solve for p: 3p + 5 = 26. What is the value of p?',
    correctAnswer: '7',
    explanation: 'Subtract 5: 3p = 21. Divide by 3: p = 7.',
    hint: 'First subtract 5, then divide by 3.',
    estimatedSeconds: 16,
  },
  {
    id: 'q-alg-6',
    subjectId: 'math',
    topicId: 'algebra',
    skillId: 'skill-linear-solve',
    gradeLevel: 6,
    difficulty: 4,
    type: 'numeric',
    prompt: 'Solve for y: 5y - 12 = 3y + 8. What is the value of y?',
    correctAnswer: '10',
    explanation: 'Subtract 3y: 2y - 12 = 8. Add 12: 2y = 20. Divide by 2: y = 10.',
    hint: 'Move all y terms to one side and constants to the other.',
    estimatedSeconds: 20,
  },
  {
    id: 'q-alg-7',
    subjectId: 'math',
    topicId: 'algebra',
    skillId: 'skill-linear-solve',
    gradeLevel: 6,
    difficulty: 5,
    type: 'numeric',
    prompt: 'Solve for w: 2(w - 4) = 3(w - 7). What is the value of w?',
    correctAnswer: '13',
    explanation: 'Distribute: 2w - 8 = 3w - 21. Subtract 2w: -8 = w - 21. Add 21: w = 13.',
    hint: 'Distribute across parentheses first.',
    estimatedSeconds: 25,
  },
];

export const ALL_EXPANDED_QUESTIONS: Question[] = [
  ...INITIAL_QUESTIONS,
  ...additionalMath,
];
